// tslint:disable max-file-line-count

export { Id } from './registry'
export {
    unpackPitchDurationContourElement,
    calculateTotalPitchDurationContourDuration,
    pitchDurationRest,
}from './contours'
export {
    adjustScalars,
    buildStandardScales,
    generateOctaveRepeatingScalars,
} from './material'
export { filter } from './filter'
export {
    standardSpecAttributes,
    standardInitialSpec,
    SpecAttributesFor,
    SpecPropertyAttributes,
    OptionedSpecPropertyAttributes,
    RangedSpecPropertyAttributes,
    ToggledSpecPropertyAttributes,
    RangedConstraint,
    OptionedConstraint,
    Constraint,
    SpecPropertyType,
    StandardSpec,
    StandardSpecProperties,
    defaultSpecPropertyAttributes,
    SpecValidationFunctionFor,
    SpecDataFor,
    SpecValidationResultsFor,
    SpecPropertyMap,
    StandardSpecAttributes,
    StandardSpecData,
    Spec,
    SpecAttributes,
    SpecData,
    SpecValidationFunction,
    SpecValidationResults,
    standardSpecData,
    OptionedConstraintOption,
    RangedInputType,
    Preset,
    PresetFor,
} from './spec'
export {
    STANDARD_DURATIONS_SCALE_INDEX,
    STANDARD_PITCH_SCALE_INDEX,
    FULL_GAIN,
} from './constants'
export {
    Segment,
    RenderingByBlockElement,
    Rendering,
    Metadata,
    Patterns,
    PatternFor,
    StandardPattern,
    Pattern,
    Presentable,
    PitchOnly,
    DurationOnly,
    GainOnly,
    SustainOnly,
    PositionOnly,
    ScaleOnly,
    PitchDuration,
    PitchGain,
    PitchSustain,
    PitchPosition,
    PitchScale,
    DurationGain,
    DurationSustain,
    DurationPosition,
    DurationScale,
    GainSustain,
    GainPosition,
    GainScale,
    SustainPosition,
    SustainScale,
    PositionScale,
    PitchDurationGain,
    PitchDurationSustain,
    PitchDurationPosition,
    PitchDurationScale,
    PitchGainSustain,
    PitchGainPosition,
    PitchGainScale,
    PitchSustainPosition,
    PitchSustainScale,
    PitchPositionScale,
    DurationGainSustain,
    DurationGainPosition,
    DurationGainScale,
    DurationPositionScale,
    GainSustainPosition,
    GainSustainScale,
    GainPositionScale,
    SustainPositionScale,
    PitchDurationGainSustain,
    PitchDurationGainPosition,
    PitchDurationGainScale,
    PitchDurationSustainPosition,
    PitchDurationPositionScale,
    PitchGainSustainPosition,
    PitchGainSustainScale,
    PitchGainPositionScale,
    PitchSustainPositionScale,
    DurationGainSustainPosition,
    DurationGainSustainScale,
    DurationGainPositionScale,
    DurationSustainPositionScale,
    GainSustainPositionScale,
    PitchDurationGainSustainPosition,
    PitchDurationGainSustainScale,
    PitchDurationGainPositionScale,
    PitchDurationSustainPositionScale,
    PitchGainSustainPositionScale,
    DurationGainSustainPositionScale,
    PitchDurationGainSustainPositionScale,
} from './types'
