// tslint:disable:no-type-definitions-outside-types-modules

enum Id {
    BEATEN_PATH = 'BEATEN_PATH',
    HAFUHAFU = 'HAFUHAFU',
    HAFUHAFU_WITH_PITCH_CIRCULARITY = 'HAFUHAFU_WITH_PITCH_CIRCULARITY',
    HOUNDSTOOTHTOPIA_THEME = 'HOUNDSTOOTHTOPIA_THEME',
    OMNIZONK = 'OMNIZONK',
    PERFORMER_QA = 'PERFORMER_QA',
    PLAYROOM_TEST_ONLY_PATTERN_PARTICULAR_SPEC = 'PLAYROOM_TEST_ONLY_PATTERN_PARTICULAR_SPEC',
    PLAYROOM_TEST_ONLY_STANDARD_SPEC = 'PLAYROOM_TEST_ONLY_STANDARD_SPEC',
    PLAYROOM_TEST_POST = 'PLAYROOM_TEST_POST',
    PLAYROOM_TEST_PRESETS = 'PLAYROOM_TEST_PRESETS',
    PLAYROOM_TEST_SPEC_CONTROLS = 'PLAYROOM_TEST_SPEC_CONTROLS',
    PLAYROOM_TEST_TIME_CONTROLS = 'PLAYROOM_TEST_TIME_CONTROLS',
    PLAYROOM_TEST_VALIDATION = 'PLAYROOM_TEST_VALIDATION',
    STEPWISE = 'STEPWISE',
    TEMPLATE = 'TEMPLATE',
    XELT = 'XELT',
    XENHARMONIC_SERIES = 'XENHARMONIC_SERIES',
    ZDAUBYAOS = 'ZDAUBYAOS',
}

export {
    Id,
}
