// tslint:disable max-file-line-count

export {
    computeTotalPitchDurationContourDuration,
    pitchDurationRest,
} from './contours'
export {
    computeNotesTotalDurationByIndex,
    computeNotesTotalDurationByScalar,
} from './notes'
export {
    materializeStandardScales,
    computeNonScale,
    computeFlatDurationsScale,
    computeHarmonicSeriesScale,
    computeOctaveSeriesScale,
    computeSubharmonicSeriesScale,
} from './scales'
export {
    PitchCircularTechnique,
    pitchCirculate,
} from './custom'

export {
    Segment,
    Rendering,
    RenderingByBlockElement,
    PitchOnly,
    DurationOnly,
    GainOnly,
    SustainOnly,
    XOnly,
    XYOnly,
    XYZOnly,
    ScaleOnly,
    PitchDuration,
    PitchGain,
    PitchSustain,
    PitchX,
    PitchXY,
    PitchXYZ,
    PitchScale,
    DurationGain,
    DurationSustain,
    DurationX,
    DurationXY,
    DurationXYZ,
    DurationScale,
    GainSustain,
    GainX,
    GainXY,
    GainXYZ,
    GainScale,
    SustainX,
    SustainXY,
    SustainXYZ,
    SustainScale,
    XScale,
    XYScale,
    XYZScale,
    PitchDurationGain,
    PitchDurationSustain,
    PitchDurationX,
    PitchDurationXY,
    PitchDurationXYZ,
    PitchDurationScale,
    PitchGainSustain,
    PitchGainX,
    PitchGainXY,
    PitchGainXYZ,
    PitchGainScale,
    PitchSustainX,
    PitchSustainXY,
    PitchSustainXYZ,
    PitchSustainScale,
    PitchXScale,
    PitchXYScale,
    PitchXYZScale,
    DurationGainSustain,
    DurationGainX,
    DurationGainXY,
    DurationGainXYZ,
    DurationGainScale,
    DurationXScale,
    DurationXYScale,
    DurationXYZScale,
    GainSustainX,
    GainSustainXY,
    GainSustainXYZ,
    GainSustainScale,
    GainXScale,
    GainXYScale,
    GainXYZScale,
    SustainXScale,
    SustainXYScale,
    SustainXYZScale,
    PitchDurationGainSustain,
    PitchDurationGainX,
    PitchDurationGainXY,
    PitchDurationGainXYZ,
    PitchDurationGainScale,
    PitchDurationSustainX,
    PitchDurationSustainXY,
    PitchDurationSustainXYZ,
    PitchDurationXScale,
    PitchDurationXYScale,
    PitchDurationXYZScale,
    PitchGainSustainX,
    PitchGainSustainXY,
    PitchGainSustainXYZ,
    PitchGainSustainScale,
    PitchGainXScale,
    PitchGainXYScale,
    PitchGainXYZScale,
    PitchSustainXScale,
    PitchSustainXYScale,
    PitchSustainXYZScale,
    DurationGainSustainX,
    DurationGainSustainXY,
    DurationGainSustainXYZ,
    DurationGainSustainScale,
    DurationGainXScale,
    DurationGainXYScale,
    DurationGainXYZScale,
    DurationSustainXScale,
    DurationSustainXYScale,
    DurationSustainXYZScale,
    GainSustainXScale,
    GainSustainXYScale,
    GainSustainXYZScale,
    PitchDurationGainSustainX,
    PitchDurationGainSustainXY,
    PitchDurationGainSustainXYZ,
    PitchDurationGainSustainScale,
    PitchDurationGainXScale,
    PitchDurationGainXYScale,
    PitchDurationGainXYZScale,
    PitchDurationSustainXScale,
    PitchDurationSustainXYScale,
    PitchDurationSustainXYZScale,
    PitchGainSustainXScale,
    PitchGainSustainXYScale,
    PitchGainSustainXYZScale,
    DurationGainSustainXScale,
    DurationGainSustainXYScale,
    DurationGainSustainXYZScale,
    PitchDurationGainSustainXScale,
    PitchDurationGainSustainXYScale,
    PitchDurationGainSustainXYZScale,
} from './types'

export {
    STANDARD_DURATIONS_SCALE_INDEX,
    STANDARD_PITCH_SCALE_INDEX,
    FULL_GAIN,
    SILENT,
    STANDARD_PITCH_INDEX_INDICATING_REST,
} from './constants'
